export const MAVLINK_V2_STX = 0xfd
export const MAVLINK_V2_HEADER_LENGTH = 10
export const MAVLINK_V2_CHECKSUM_LENGTH = 2
export const MAVLINK_V2_SIGNATURE_LENGTH = 13
export const MAVLINK_V2_INCOMPAT_FLAG_SIGNED = 0x01

export const MAVLINK_MESSAGE_IDS = {
  HEARTBEAT: 0,
  SYS_STATUS: 1,
  GLOBAL_POSITION_INT: 33,
  PARAM_REQUEST_LIST: 21,
  PARAM_VALUE: 22,
  PARAM_SET: 23,
  ATTITUDE: 30,
  RC_CHANNELS: 65,
  FILE_TRANSFER_PROTOCOL: 110,
  COMMAND_ACK: 77,
  COMMAND_LONG: 76,
  AUTOPILOT_VERSION: 148,
  STATUSTEXT: 253
} as const

export const MAVLINK_MESSAGE_CRCS: Record<number, number> = {
  [MAVLINK_MESSAGE_IDS.HEARTBEAT]: 50,
  [MAVLINK_MESSAGE_IDS.SYS_STATUS]: 124,
  [MAVLINK_MESSAGE_IDS.GLOBAL_POSITION_INT]: 104,
  [MAVLINK_MESSAGE_IDS.PARAM_REQUEST_LIST]: 159,
  [MAVLINK_MESSAGE_IDS.PARAM_VALUE]: 220,
  [MAVLINK_MESSAGE_IDS.PARAM_SET]: 168,
  [MAVLINK_MESSAGE_IDS.ATTITUDE]: 39,
  [MAVLINK_MESSAGE_IDS.RC_CHANNELS]: 118,
  [MAVLINK_MESSAGE_IDS.FILE_TRANSFER_PROTOCOL]: 84,
  [MAVLINK_MESSAGE_IDS.COMMAND_ACK]: 143,
  [MAVLINK_MESSAGE_IDS.COMMAND_LONG]: 152,
  [MAVLINK_MESSAGE_IDS.AUTOPILOT_VERSION]: 178,
  [MAVLINK_MESSAGE_IDS.STATUSTEXT]: 83
}

export const MAVLINK_PAYLOAD_LENGTHS: Record<number, number> = {
  [MAVLINK_MESSAGE_IDS.HEARTBEAT]: 9,
  [MAVLINK_MESSAGE_IDS.SYS_STATUS]: 43,
  [MAVLINK_MESSAGE_IDS.GLOBAL_POSITION_INT]: 28,
  [MAVLINK_MESSAGE_IDS.PARAM_REQUEST_LIST]: 2,
  [MAVLINK_MESSAGE_IDS.PARAM_VALUE]: 25,
  [MAVLINK_MESSAGE_IDS.PARAM_SET]: 23,
  [MAVLINK_MESSAGE_IDS.ATTITUDE]: 28,
  [MAVLINK_MESSAGE_IDS.RC_CHANNELS]: 42,
  [MAVLINK_MESSAGE_IDS.FILE_TRANSFER_PROTOCOL]: 254,
  [MAVLINK_MESSAGE_IDS.COMMAND_ACK]: 10,
  [MAVLINK_MESSAGE_IDS.COMMAND_LONG]: 33,
  [MAVLINK_MESSAGE_IDS.AUTOPILOT_VERSION]: 78,
  [MAVLINK_MESSAGE_IDS.STATUSTEXT]: 54
}

export const MAVLINK_MIN_PAYLOAD_LENGTHS: Record<number, number> = {
  [MAVLINK_MESSAGE_IDS.HEARTBEAT]: 9,
  [MAVLINK_MESSAGE_IDS.SYS_STATUS]: 31,
  [MAVLINK_MESSAGE_IDS.GLOBAL_POSITION_INT]: 28,
  [MAVLINK_MESSAGE_IDS.PARAM_REQUEST_LIST]: 2,
  [MAVLINK_MESSAGE_IDS.PARAM_VALUE]: 25,
  [MAVLINK_MESSAGE_IDS.PARAM_SET]: 23,
  [MAVLINK_MESSAGE_IDS.ATTITUDE]: 28,
  [MAVLINK_MESSAGE_IDS.RC_CHANNELS]: 42,
  [MAVLINK_MESSAGE_IDS.FILE_TRANSFER_PROTOCOL]: 254,
  [MAVLINK_MESSAGE_IDS.COMMAND_ACK]: 3,
  [MAVLINK_MESSAGE_IDS.COMMAND_LONG]: 33,
  [MAVLINK_MESSAGE_IDS.AUTOPILOT_VERSION]: 60,
  [MAVLINK_MESSAGE_IDS.STATUSTEXT]: 51
}

export const MAVLINK_PROTOCOL_VERSION = 3

export const MAV_AUTOPILOT = {
  ARDUPILOTMEGA: 3,
  INVALID: 8
} as const

export const MAV_TYPE = {
  GENERIC: 0,
  QUADROTOR: 2,
  HEXAROTOR: 13,
  OCTOROTOR: 14,
  TRICOPTER: 15,
  HELICOPTER: 4
} as const

export const MAV_MODE_FLAG = {
  CUSTOM_MODE_ENABLED: 1,
  SAFETY_ARMED: 128
} as const

export const MAV_STATE = {
  STANDBY: 3,
  ACTIVE: 4
} as const

export const MAV_SEVERITY = {
  EMERGENCY: 0,
  ALERT: 1,
  CRITICAL: 2,
  ERROR: 3,
  WARNING: 4,
  NOTICE: 5,
  INFO: 6,
  DEBUG: 7
} as const

export const MAV_PARAM_TYPE = {
  UINT8: 1,
  INT8: 2,
  UINT16: 3,
  INT16: 4,
  UINT32: 5,
  INT32: 6,
  UINT64: 7,
  INT64: 8,
  REAL32: 9,
  REAL64: 10
} as const

export const MAV_CMD = {
  DO_SET_MODE: 176,
  DO_MOTOR_TEST: 209,
  PREFLIGHT_CALIBRATION: 241,
  PREFLIGHT_REBOOT_SHUTDOWN: 246,
  SET_MESSAGE_INTERVAL: 511,
  REQUEST_MESSAGE: 512,
  REQUEST_AUTOPILOT_CAPABILITIES: 520,
  ACCELCAL_VEHICLE_POS: 42429
} as const

export const MAV_PROTOCOL_CAPABILITY = {
  FTP: 128n
} as const

export const MAV_FTP_OPCODE = {
  NONE: 0,
  TERMINATE_SESSION: 1,
  RESET_SESSIONS: 2,
  LIST_DIRECTORY: 3,
  OPEN_FILE_RO: 4,
  READ_FILE: 5,
  CREATE_FILE: 6,
  WRITE_FILE: 7,
  REMOVE_FILE: 8,
  CREATE_DIRECTORY: 9,
  REMOVE_DIRECTORY: 10,
  OPEN_FILE_WO: 11,
  TRUNCATE_FILE: 12,
  RENAME: 13,
  CALC_FILE_CRC32: 14,
  BURST_READ_FILE: 15,
  ACK: 128,
  NAK: 129
} as const

export const MAV_FTP_ERR = {
  NONE: 0,
  FAIL: 1,
  FAIL_ERRNO: 2,
  INVALID_DATA_SIZE: 3,
  INVALID_SESSION: 4,
  NO_SESSIONS_AVAILABLE: 5,
  EOF: 6,
  UNKNOWN_COMMAND: 7,
  FILE_EXISTS: 8,
  FILE_PROTECTED: 9,
  FILE_NOT_FOUND: 10
} as const

export const MOTOR_TEST_THROTTLE_TYPE = {
  PERCENT: 0,
  PWM: 1,
  PILOT: 2,
  CAL: 3
} as const

export const MOTOR_TEST_ORDER = {
  DEFAULT: 0,
  SEQUENCE: 1,
  BOARD: 2
} as const

export const MAV_RESULT = {
  ACCEPTED: 0,
  TEMPORARILY_REJECTED: 1,
  DENIED: 2,
  UNSUPPORTED: 3,
  FAILED: 4,
  IN_PROGRESS: 5
} as const
